dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.6.3

addons:
  postgresql: "10"

before_script:
  - psql -c 'create database "array_enum_test";' -U postgres

script: "bundle exec rake"

notifications:
  disabled: true
