name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
        - 5432:5432
        env:
          POSTGRES_PASSWORD: ""

    steps:
    - name: Install libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev postgresql-client

    - name: Configure database
      run: |
        echo "PostgreSQL"
        psql -h localhost -c 'create database "array_enum_test";' -U postgres

    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Build and test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake test
